version: 2
jobs:
  build:
    docker:
      - image: selenium/standalone-chrome-debug
    steps:
      - checkout

      - restore_cache:
          keys:
          - m2-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - m2-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

      - run: cd /home/circleci/project/src/test/resources/drivers/ && chmod +x chromedriver
      - run: mvn test -Dmaven.test.skip=false
