version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - checkout

      - restore_cache:
          keys:
          - m2-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - m2-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

      - run: cd /home/circleci/project/src/test/resources/drivers/ && chmod +x chromedriver
      - run: mvn test -Dmaven.test.skip=false
