version: 2
jobs:
  build:
    working_directory: ~/circleci-testng-webdriver
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

      - run: mvn test -D maven.test.skip=false

      - store_test_results:
          path: target/surefire-reports
